<?php require APP_PATH . 'Views/layouts/header.php'; require APP_PATH . 'Views/layouts/sidebar.php'; ?>
<div id="main-content"><?php require APP_PATH . 'Views/layouts/navbar.php'; ?>
 <div class="glass-card dashboard-toolbar mb-4 mt-3"><div class="d-flex align-items-center justify-content-between"><div><div class="section-kicker">EMPLOYEE SELF-SERVICE</div><h5 class="section-heading mb-0">Welcome, <?= htmlspecialchars($user['full_name']); ?></h5></div><a href="index.php?page=notifications" class="btn btn-outline-primary btn-sm"><i class="fa-regular fa-bell me-2"></i>Notifications</a></div></div>
 <div class="reporting-scope mb-4"><div class="scope-icon"><i class="fa-regular fa-user"></i></div><div><span>MY EMPLOYEE RECORD</span><strong>Personal dashboard and self-service activity</strong><small>Only information linked to your authenticated employee account is shown.</small></div></div>
 <div class="section-kicker">MY STATUS</div><h5 class="section-heading">Employee Overview</h5>
 <div class="row g-3 mb-4 executive-cards core-kpi-grid">
  <?php $cards=[['My Training',count($registrations),'fa-graduation-cap','#5145e5'],['Completed Training',$training_completed,'fa-circle-check','#16a34a'],['My Documents',count($documents),'fa-folder-open','#0284c7'],['Pending Claims',$pending_claims,'fa-clock','#d97706']]; foreach($cards as $card): ?>
  <div class="col-xl-3 col-sm-6"><div class="glass-card stat-card"><div class="text-secondary small fw-bold text-uppercase"><?= $card[0]; ?></div><h3 class="fw-bold mt-2 mb-1" style="color:<?= $card[3]; ?>"><?= $card[1]; ?></h3><span class="text-secondary small">Your current records</span><i class="fa-solid <?= $card[2]; ?> stat-icon-bg"></i></div></div><?php endforeach; ?>
 </div>
 <div class="section-kicker">QUICK ACCESS</div><h5 class="section-heading">My Employee Services</h5>
 <div class="row g-3 mb-4"><?php $links=[['training','My Development','Assigned courses, assessments and certificates','fa-graduation-cap'],['documents','My Documents','Personal files, contracts and document status','fa-folder-open'],['compliance','My Contributions','SSS, PhilHealth and Pag-IBIG history','fa-landmark'],['benefits','My Benefits & Loans','Claims, applications and balances','fa-hand-holding-dollar'],['separation','My Clearance','Offboarding requirements and status','fa-plane-departure'],['my_profile','My Profile','Personal and employment information','fa-user']]; foreach($links as $link): ?><div class="col-lg-4 col-md-6"><a href="index.php?page=<?= $link[0]; ?>" class="glass-card p-3 d-flex align-items-center gap-3 text-decoration-none h-100"><div class="scope-icon mb-0"><i class="fa-solid <?= $link[3]; ?>"></i></div><div><strong class="d-block text-dark"><?= $link[1]; ?></strong><small class="text-secondary"><?= $link[2]; ?></small></div></a></div><?php endforeach; ?></div>
</div><?php require APP_PATH . 'Views/layouts/footer.php'; ?>
