<?php require APP_PATH . 'Views/layouts/header.php'; require APP_PATH . 'Views/layouts/sidebar.php'; $isAdmin=Auth::isAdmin();$csrf=csrf_token(); ?>
<div id="main-content"><?php require APP_PATH . 'Views/layouts/navbar.php'; ?>
 <div class="d-flex align-items-center justify-content-between my-3 flex-wrap gap-2"><div><a href="index.php?page=training" class="btn btn-outline-secondary btn-sm mb-2"><i class="fa-solid fa-arrow-left"></i>Back to Training</a><h4><i class="fa-solid fa-book-open"></i>Training Course Library</h4><p class="text-secondary mb-0"><?= $isAdmin?'Complete training catalogue and scheduling register':'Browse available training programs and monitor enrollment availability'; ?></p></div><?php if($isAdmin): ?><a href="index.php?page=training" class="btn btn-primary btn-sm"><i class="fa-solid fa-plus"></i>Create or Manage Training</a><?php endif; ?></div>
 <div class="glass-card p-4 mb-4"><div class="table-responsive"><table class="table align-middle datatable-init"><thead><tr><th>Training</th><th>Category / Type</th><th>Schedule</th><th>Trainer / Venue</th><th>Status</th><th>Capacity</th><th>Actions</th></tr></thead><tbody>
 <?php foreach($courses as $course): $registered=!$isAdmin&&!empty($course['registration_id']);$full=(int)$course['enrolled_count']>=max(1,(int)$course['capacity']); ?><tr><td><strong><?= htmlspecialchars($course['title']); ?></strong><small class="d-block text-secondary"><?= htmlspecialchars($course['description']); ?></small></td><td><?= htmlspecialchars($course['category_name']??'General'); ?><small class="d-block text-secondary"><?= htmlspecialchars($course['course_type']); ?></small></td><td><?= date('M j, Y',strtotime($course['start_date'])); ?><small class="d-block text-secondary">to <?= date('M j, Y',strtotime($course['end_date'])); ?></small></td><td><?= htmlspecialchars($course['trainer_name']??'Internal HR'); ?><small class="d-block text-secondary"><?= htmlspecialchars($course['venue']); ?></small></td><td><span class="badge badge-soft-primary"><?= htmlspecialchars($course['status']); ?></span></td><td><?= (int)$course['enrolled_count']; ?> / <?= (int)$course['capacity']; ?></td><td><div class="table-action-group"><a class="btn btn-outline-primary btn-sm" href="index.php?page=training_details&amp;id=<?= (int)$course['id']; ?>">Details</a><?php if(!$isAdmin&&!$registered): ?><button class="btn btn-primary btn-sm btn-apply" data-id="<?= (int)$course['id']; ?>" <?= $full?'disabled':''; ?>><?= $full?'Full':'Apply'; ?></button><?php elseif($registered): ?><span class="badge badge-soft-info"><?= htmlspecialchars($course['participation_status']); ?></span><?php endif; ?></div></td></tr><?php endforeach; ?>
 </tbody></table></div></div>
</div>
<?php if(!$isAdmin): ?><script>$(function(){$('.btn-apply').on('click',function(){const id=$(this).data('id');confirmAction('Apply for Training','Submit your application for Admin/HR review?','Apply',function(){$.post('index.php?page=training_register',{course_id:id,csrf_token:<?= json_encode($csrf); ?>},function(res){if(res.status==='success'){showToast('success',res.message);setTimeout(()=>location.reload(),800)}else Swal.fire('Notice',res.message,res.status==='warning'?'warning':'error')},'json')})})});</script><?php endif; ?>
<?php require APP_PATH . 'Views/layouts/footer.php'; ?>
