-- Phase 5: Document and Contract Management workflow (idempotent).
ALTER TABLE document_categories ADD COLUMN IF NOT EXISTS description TEXT NULL AFTER name, ADD COLUMN IF NOT EXISTS instructions TEXT NULL AFTER is_required, ADD COLUMN IF NOT EXISTS allowed_extensions VARCHAR(120) NOT NULL DEFAULT 'pdf,jpg,jpeg,png' AFTER instructions, ADD COLUMN IF NOT EXISTS max_size_mb INT NOT NULL DEFAULT 5 AFTER allowed_extensions, ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1 AFTER max_size_mb, ADD UNIQUE INDEX IF NOT EXISTS uq_document_category_name (name);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS requirement_id INT NULL AFTER category_id, ADD COLUMN IF NOT EXISTS issue_date DATE NULL AFTER file_size, ADD COLUMN IF NOT EXISTS remarks TEXT NULL AFTER status, ADD COLUMN IF NOT EXISTS original_name VARCHAR(255) NULL AFTER remarks, ADD COLUMN IF NOT EXISTS mime_type VARCHAR(120) NULL AFTER original_name, ADD COLUMN IF NOT EXISTS version_no INT NOT NULL DEFAULT 1 AFTER mime_type, ADD COLUMN IF NOT EXISTS replaces_document_id INT NULL AFTER version_no, ADD COLUMN IF NOT EXISTS submitted_by INT NULL AFTER replaces_document_id, ADD COLUMN IF NOT EXISTS reviewed_by INT NULL AFTER submitted_by, ADD COLUMN IF NOT EXISTS reviewed_at DATETIME NULL AFTER reviewed_by, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER upload_date;
ALTER TABLE documents MODIFY COLUMN status VARCHAR(30) NOT NULL DEFAULT 'Pending';
UPDATE documents SET status='Approved' WHERE status='Verified';
ALTER TABLE documents MODIFY COLUMN status ENUM('Pending','Submitted','Under Review','Approved','Returned','Rejected','Expired','Renewal Required') NOT NULL DEFAULT 'Pending';
CREATE TABLE IF NOT EXISTS document_requirements (id INT AUTO_INCREMENT PRIMARY KEY,employee_id INT NOT NULL,category_id INT NOT NULL,title VARCHAR(150) NOT NULL,instructions TEXT NULL,due_date DATE NULL,status ENUM('Pending','Submitted','Under Review','Approved','Returned','Rejected','Expired','Renewal Required') NOT NULL DEFAULT 'Pending',current_document_id INT NULL,assigned_by INT NULL,acknowledged_at DATETIME NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_requirement_employee_status (employee_id,status),FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,FOREIGN KEY (category_id) REFERENCES document_categories(id),FOREIGN KEY (current_document_id) REFERENCES documents(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS document_versions (id INT AUTO_INCREMENT PRIMARY KEY,document_id INT NOT NULL,version_no INT NOT NULL,file_path VARCHAR(255) NOT NULL,original_name VARCHAR(255) NULL,file_size VARCHAR(50) NULL,mime_type VARCHAR(120) NULL,status VARCHAR(30) NOT NULL,remarks TEXT NULL,archived_by INT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_document_version (document_id,version_no),FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE) ENGINE=InnoDB;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS version_no INT NOT NULL DEFAULT 1 AFTER contract_type, ADD COLUMN IF NOT EXISTS previous_contract_id INT NULL AFTER version_no, ADD COLUMN IF NOT EXISTS remarks TEXT NULL AFTER document_file, ADD COLUMN IF NOT EXISTS original_name VARCHAR(255) NULL AFTER remarks, ADD COLUMN IF NOT EXISTS acknowledged_at DATETIME NULL AFTER original_name, ADD COLUMN IF NOT EXISTS renewed_at DATETIME NULL AFTER acknowledged_at, ADD COLUMN IF NOT EXISTS created_by INT NULL AFTER renewed_at, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at, ADD INDEX IF NOT EXISTS idx_contract_employee_end (employee_id,end_date);
ALTER TABLE contracts MODIFY COLUMN status ENUM('Draft','Active','Renewed','Expired','Terminated','Archived') NOT NULL DEFAULT 'Active';
