<?php
require_once ROOT_PATH.'core/Controller.php';
require_once APP_PATH.'Models/Report.php';
class ReportController extends Controller {
    private $reports;
    public function __construct(){$this->reports=new Report();}
    public function index(){Auth::requireRole(['Super Admin','HR Manager']);$defs=$this->reports->definitions();$key=$_GET['report']??'training_participation';if(!isset($defs[$key]))$key='training_participation';$filters=$this->filters();$result=$this->reports->result($key,$filters,(int)($_GET['p']??1));$this->view('reports/index',['definitions'=>$defs,'report_key'=>$key,'report'=>$defs[$key],'filters'=>$filters,'result'=>$result,'options'=>$this->reports->options()]);}
    public function export(){Auth::requireRole(['Super Admin','HR Manager']);$defs=$this->reports->definitions();$key=$_GET['report']??'';if(!isset($defs[$key])){http_response_code(404);exit('Report not found.');}$rows=$this->reports->rows($key,$this->filters());$name=preg_replace('/[^a-z0-9-]+/','-',strtolower($defs[$key][0])).'-'.date('Ymd').'.csv';header('Content-Type:text/csv; charset=UTF-8');header('Content-Disposition:attachment; filename="'.$name.'"');header('X-Content-Type-Options:nosniff');$out=fopen('php://output','w');fputcsv($out,['Record ID','Employee Code','Employee','Department','Status','Type','Date','Amount / Percentage','Details']);foreach($rows as $row)fputcsv($out,[$row['record_id'],$row['employee_code'],$row['employee'],$row['department'],$row['status'],$row['type'],$row['event_date'],$row['amount'],$row['detail']]);fclose($out);AuditLogger::log('EXPORT_REPORT','Reports',$defs[$key][0].' exported with '.count($rows).' rows.',null,['record_type'=>'report','new_value'=>['report'=>$key,'rows'=>count($rows)]]);exit;}
    private function filters(){$date=fn($v)=>preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)$v)?$v:'';return ['date_from'=>$date($_GET['date_from']??''),'date_to'=>$date($_GET['date_to']??''),'employee_id'=>max(0,(int)($_GET['employee_id']??0)),'department_id'=>max(0,(int)($_GET['department_id']??0)),'status'=>trim($_GET['status']??''),'type'=>trim($_GET['type']??''),'month'=>max(0,min(12,(int)($_GET['month']??0))),'year'=>max(0,min(2100,(int)($_GET['year']??0)))];}
}
