<?php
require_once ROOT_PATH . 'core/Model.php';

class Report extends Model {
    public function definitions() {
        $employee="e.employee_code,CONCAT(e.first_name,' ',e.last_name) employee,d.name department,e.id employee_id,e.department_id";
        return [
            'training_participation'=>['Training Participation','Training',"SELECT tr.id record_id,$employee,tr.status,tc.course_type type,DATE(tr.registration_date) event_date,NULL amount,tc.title detail FROM training_registrations tr JOIN training_courses tc ON tc.id=tr.course_id JOIN employees e ON e.id=tr.employee_id LEFT JOIN departments d ON d.id=e.department_id"],
            'training_completion'=>['Training Completion','Training',"SELECT tr.id record_id,$employee,tr.status,tc.course_type type,tc.end_date event_date,NULL amount,tc.title detail FROM training_registrations tr JOIN training_courses tc ON tc.id=tr.course_id JOIN employees e ON e.id=tr.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE tr.status='Completed'"],
            'training_attendance'=>['Training Attendance','Training',"SELECT tr.id record_id,$employee,tr.status,tc.course_type type,tc.start_date event_date,tr.attendance_percentage amount,CONCAT(tc.title,' - attendance %') detail FROM training_registrations tr JOIN training_courses tc ON tc.id=tr.course_id JOIN employees e ON e.id=tr.employee_id LEFT JOIN departments d ON d.id=e.department_id"],
            'training_certificates'=>['Certificates Issued','Training',"SELECT tr.id record_id,$employee,tr.status,tc.course_type type,tc.end_date event_date,NULL amount,tc.title detail FROM training_registrations tr JOIN training_courses tc ON tc.id=tr.course_id JOIN employees e ON e.id=tr.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE tr.certificate_file IS NOT NULL"],
            'documents_pending'=>['Pending Documents','Documents',"SELECT x.id record_id,$employee,x.status,dc.name type,DATE(x.upload_date) event_date,NULL amount,x.title detail FROM documents x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN document_categories dc ON dc.id=x.category_id WHERE x.status IN ('Pending','Submitted','Under Review','Returned')"],
            'documents_approved'=>['Approved Documents','Documents',"SELECT x.id record_id,$employee,x.status,dc.name type,DATE(x.reviewed_at) event_date,NULL amount,x.title detail FROM documents x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN document_categories dc ON dc.id=x.category_id WHERE x.status='Approved'"],
            'documents_expired'=>['Expired Documents','Documents',"SELECT x.id record_id,$employee,x.status,dc.name type,x.expiry_date event_date,NULL amount,x.title detail FROM documents x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN document_categories dc ON dc.id=x.category_id WHERE x.status='Expired' OR x.expiry_date<CURRENT_DATE"],
            'documents_expiring'=>['Expiring Documents','Documents',"SELECT x.id record_id,$employee,x.status,dc.name type,x.expiry_date event_date,NULL amount,x.title detail FROM documents x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN document_categories dc ON dc.id=x.category_id WHERE x.expiry_date BETWEEN CURRENT_DATE AND DATE_ADD(CURRENT_DATE,INTERVAL 30 DAY)"],
            'documents_missing'=>['Missing Requirements','Documents',"SELECT x.id record_id,$employee,x.status,dc.name type,x.due_date event_date,NULL amount,x.title detail FROM document_requirements x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN document_categories dc ON dc.id=x.category_id WHERE x.is_active=1 AND (x.current_document_id IS NULL OR x.status IN ('Pending','Returned','Rejected','Expired','Renewal Required'))"],
            'contracts_active'=>['Active Contracts','Contracts',"SELECT x.id record_id,$employee,x.status,x.contract_type type,x.start_date event_date,NULL amount,CONCAT('Ends ',COALESCE(x.end_date,'open')) detail FROM contracts x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE x.status='Active'"],
            'contracts_expiring'=>['Expiring Contracts','Contracts',"SELECT x.id record_id,$employee,x.status,x.contract_type type,x.end_date event_date,NULL amount,CONCAT('Version ',x.version_no) detail FROM contracts x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE x.status='Active' AND x.end_date BETWEEN CURRENT_DATE AND DATE_ADD(CURRENT_DATE,INTERVAL 60 DAY)"],
            'contracts_renewal'=>['Renewal Required','Contracts',"SELECT x.id record_id,$employee,x.status,x.contract_type type,x.end_date event_date,NULL amount,CONCAT('Version ',x.version_no) detail FROM contracts x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE x.status='Expired' OR (x.status='Active' AND x.end_date<CURRENT_DATE)"],
            'compliance_missing'=>['Missing Government Records','Compliance',"SELECT x.id record_id,$employee,x.status,x.agency type,DATE(x.updated_at) event_date,NULL amount,'Government identifier missing' detail FROM government_records x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE x.status='Missing' OR x.record_number IS NULL OR x.record_number=''"],
            'compliance_verified'=>['Verified Government Records','Compliance',"SELECT x.id record_id,$employee,x.status,x.agency type,DATE(x.verified_at) event_date,NULL amount,'Verified government identifier' detail FROM government_records x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE x.status='Verified'"],
            'compliance_pending'=>['Pending Verification','Compliance',"SELECT x.id record_id,$employee,x.status,x.agency type,DATE(x.updated_at) event_date,NULL amount,'Awaiting HR verification' detail FROM government_records x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE x.status IN ('Submitted','Pending Verification','Needs Correction')"],
            'compliance_contributions'=>['Contribution Summary','Compliance',"SELECT x.id record_id,$employee,x.status,'Statutory' type,STR_TO_DATE(CONCAT(x.period_year,'-',LPAD(x.period_month,2,'0'),'-01'),'%Y-%m-%d') event_date,x.total_statutory amount,CONCAT('Gross PHP ',FORMAT(x.gross_salary,2)) detail FROM gov_contributions x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id"],
            'compliance_corrections'=>['Correction Requests','Compliance',"SELECT x.id record_id,$employee,x.status,gr.agency type,DATE(x.created_at) event_date,NULL amount,x.reason detail FROM government_corrections x JOIN government_records gr ON gr.id=x.government_record_id JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id"],
            'benefits_applications'=>['Benefit Applications by Status','Benefits',"SELECT x.id record_id,$employee,x.status,b.type,DATE(x.submitted_at) event_date,x.amount,x.claim_type detail FROM benefit_claims x JOIN benefit_plans b ON b.id=x.benefit_id JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id"],
            'benefits_approved'=>['Approved Benefits','Benefits',"SELECT x.id record_id,$employee,x.status,b.type,DATE(x.reviewed_at) event_date,x.amount,x.claim_type detail FROM benefit_claims x JOIN benefit_plans b ON b.id=x.benefit_id JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE x.status='Approved'"],
            'benefits_released'=>['Released Benefits','Benefits',"SELECT x.id record_id,$employee,x.status,b.type,DATE(x.released_at) event_date,x.amount,x.claim_type detail FROM benefit_claims x JOIN benefit_plans b ON b.id=x.benefit_id JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE x.status IN ('Released','Completed')"],
            'benefits_usage'=>['Benefit Usage','Benefits',"SELECT x.id record_id,$employee,x.status,b.type,DATE(COALESCE(x.completed_at,x.released_at)) event_date,x.amount,b.name detail FROM benefit_claims x JOIN benefit_plans b ON b.id=x.benefit_id JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE x.status IN ('Released','Completed')"],
            'loans_applications'=>['Loan Applications','Loans',"SELECT x.id record_id,$employee,x.status,x.loan_type type,DATE(x.requested_at) event_date,x.requested_amount amount,CONCAT(x.term_months,' months') detail FROM loans x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id"],
            'loans_active'=>['Active Loans','Loans',"SELECT x.id record_id,$employee,x.status,x.loan_type type,x.release_date event_date,x.approved_amount amount,CONCAT('Balance PHP ',FORMAT(x.balance_remaining,2)) detail FROM loans x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE x.status='Active'"],
            'loans_paid'=>['Paid Loans','Loans',"SELECT x.id record_id,$employee,x.status,x.loan_type type,DATE(x.paid_at) event_date,x.approved_amount amount,'Balance PHP 0.00' detail FROM loans x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE x.status='Paid'"],
            'loans_balances'=>['Remaining Loan Balances','Loans',"SELECT x.id record_id,$employee,x.status,x.loan_type type,COALESCE(x.release_date,DATE(x.requested_at)) event_date,x.balance_remaining amount,CONCAT('Approved PHP ',FORMAT(COALESCE(x.approved_amount,0),2)) detail FROM loans x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE x.status IN ('Approved','Released','Active')"],
            'loans_payments'=>['Loan Payment History','Loans',"SELECT p.id record_id,$employee,x.status,x.loan_type type,p.payment_date event_date,p.amount,CONCAT(p.payment_method,COALESCE(CONCAT(' - ',p.reference_no),'')) detail FROM loan_payments p JOIN loans x ON x.id=p.loan_id JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id"],
            'separation_requests'=>['Separation Requests','Separation',"SELECT x.id record_id,$employee,x.status,x.separation_type type,x.notice_date event_date,NULL amount,x.reason detail FROM separations x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id"],
            'separation_types'=>['Separation Types','Separation',"SELECT x.id record_id,$employee,x.status,x.separation_type type,x.notice_date event_date,NULL amount,x.reason detail FROM separations x JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id"],
            'separation_pending_clearance'=>['Pending Clearances','Separation',"SELECT c.id record_id,$employee,c.status,c.department_name type,DATE(c.updated_at) event_date,NULL amount,COALESCE(c.accountability_details,'Awaiting clearance') detail FROM clearances c JOIN separations x ON x.id=c.separation_id JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE c.status<>'Cleared'"],
            'separation_completed_clearance'=>['Completed Clearances','Separation',"SELECT c.id record_id,$employee,c.status,c.department_name type,DATE(c.clearance_date) event_date,NULL amount,'Department cleared' detail FROM clearances c JOIN separations x ON x.id=c.separation_id JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE c.status='Cleared'"],
        ];
    }

    public function rows($key,array $filters=[], $limit=null, $offset=0) {
        $defs=$this->definitions();if(!isset($defs[$key]))throw new InvalidArgumentException('Unknown report.');
        $sql='SELECT * FROM ('.$defs[$key][2].') report WHERE 1=1';$params=[];
        foreach(['employee_id','department_id'] as $field)if(!empty($filters[$field])){$sql.=" AND {$field}=?";$params[]=(int)$filters[$field];}
        foreach(['status','type'] as $field)if(($filters[$field]??'')!==''){$sql.=" AND {$field}=?";$params[]=$filters[$field];}
        if(!empty($filters['date_from'])){$sql.=' AND event_date>=?';$params[]=$filters['date_from'];}
        if(!empty($filters['date_to'])){$sql.=' AND event_date<=?';$params[]=$filters['date_to'];}
        if(!empty($filters['month'])){$sql.=' AND MONTH(event_date)=?';$params[]=(int)$filters['month'];}
        if(!empty($filters['year'])){$sql.=' AND YEAR(event_date)=?';$params[]=(int)$filters['year'];}
        $sql.=' ORDER BY event_date DESC,record_id DESC';if($limit!==null)$sql.=' LIMIT '.max(1,(int)$limit).' OFFSET '.max(0,(int)$offset);
        return $this->db->fetchAll($sql,$params);
    }

    public function result($key,array $filters,$page=1,$perPage=20) {
        $all=$this->rows($key,$filters);$total=count($all);$amount=array_sum(array_map(fn($r)=>(float)($r['amount']??0),$all));$page=max(1,(int)$page);$pages=max(1,(int)ceil($total/$perPage));$page=min($page,$pages);
        return ['rows'=>array_slice($all,($page-1)*$perPage,$perPage),'total'=>$total,'amount'=>$amount,'page'=>$page,'pages'=>$pages];
    }

    public function options() {
        return ['employees'=>$this->db->fetchAll("SELECT id,employee_code,first_name,last_name FROM employees ORDER BY last_name,first_name"),'departments'=>$this->db->fetchAll("SELECT id,name FROM departments ORDER BY name")];
    }
}
