<?php require APP_PATH.'Views/layouts/header.php';require APP_PATH.'Views/layouts/sidebar.php';$query=$_GET;unset($query['p']);$export=$query;$export['page']='reports_export';$money=in_array($report_key,['compliance_contributions','benefits_applications','benefits_approved','benefits_released','benefits_usage','loans_applications','loans_active','loans_paid','loans_balances','loans_payments'],true); ?>
<div id="main-content"><?php require APP_PATH.'Views/layouts/navbar.php'; ?>
 <div class="module-toolbar my-3"><div class="module-toolbar-title"><span class="module-toolbar-icon"><i class="fa-solid fa-chart-pie"></i></span><div><h5>Functional Reports</h5><small>Verified operational reports generated from current database records</small></div></div><a class="btn btn-primary btn-sm" href="?<?= htmlspecialchars(http_build_query($export)); ?>"><i class="fa-solid fa-file-csv me-1"></i>Export Current CSV</a></div>
 <div class="glass-card p-3 mb-4"><div class="row g-3">
 <?php $group='';foreach($definitions as $key=>$definition):if($group!==$definition[1]):if($group!==''):?></div></div><?php endif;$group=$definition[1];?><div class="col-xl-3 col-md-6"><div class="section-kicker mb-2"><?= htmlspecialchars(strtoupper($group)); ?></div><div class="d-flex flex-column gap-1"><?php endif; ?>
  <a class="btn btn-sm text-start <?= $key===$report_key?'btn-primary':'btn-outline-secondary'; ?>" href="index.php?page=reports&amp;report=<?= urlencode($key); ?>"><?= htmlspecialchars($definition[0]); ?></a>
 <?php endforeach;if($group!==''):?></div></div><?php endif; ?>
 </div></div>
 <form class="glass-card p-3 mb-4" method="get"><input type="hidden" name="page" value="reports"><input type="hidden" name="report" value="<?= htmlspecialchars($report_key); ?>"><div class="row g-2 align-items-end">
  <div class="col-sm-6 col-lg-2"><label class="form-label small">From date</label><input type="date" class="form-control" name="date_from" value="<?= htmlspecialchars($filters['date_from']); ?>"></div>
  <div class="col-sm-6 col-lg-2"><label class="form-label small">To date</label><input type="date" class="form-control" name="date_to" value="<?= htmlspecialchars($filters['date_to']); ?>"></div>
  <div class="col-sm-6 col-lg-2"><label class="form-label small">Employee</label><select class="form-select" name="employee_id"><option value="">All employees</option><?php foreach($options['employees'] as $e):?><option value="<?= (int)$e['id']; ?>" <?= (int)$filters['employee_id']===(int)$e['id']?'selected':''; ?>><?= htmlspecialchars($e['employee_code'].' - '.$e['first_name'].' '.$e['last_name']); ?></option><?php endforeach;?></select></div>
  <div class="col-sm-6 col-lg-2"><label class="form-label small">Department</label><select class="form-select" name="department_id"><option value="">All departments</option><?php foreach($options['departments'] as $d):?><option value="<?= (int)$d['id']; ?>" <?= (int)$filters['department_id']===(int)$d['id']?'selected':''; ?>><?= htmlspecialchars($d['name']); ?></option><?php endforeach;?></select></div>
  <div class="col-sm-6 col-lg-2"><label class="form-label small">Status</label><input class="form-control" name="status" value="<?= htmlspecialchars($filters['status']); ?>" placeholder="Exact status"></div>
  <div class="col-sm-6 col-lg-2"><label class="form-label small">Type</label><input class="form-control" name="type" value="<?= htmlspecialchars($filters['type']); ?>" placeholder="Exact type"></div>
  <div class="col-sm-4 col-lg-1"><label class="form-label small">Month</label><select class="form-select" name="month"><option value="">All</option><?php for($m=1;$m<=12;$m++):?><option value="<?= $m; ?>" <?= $filters['month']===$m?'selected':''; ?>><?= date('M',mktime(0,0,0,$m,1)); ?></option><?php endfor;?></select></div>
  <div class="col-sm-4 col-lg-1"><label class="form-label small">Year</label><input class="form-control" type="number" min="2000" max="2100" name="year" value="<?= $filters['year']?:''; ?>"></div>
  <div class="col-sm-4 col-lg-2 d-flex gap-2"><button class="btn btn-primary" type="submit">Apply</button><a class="btn btn-outline-secondary" href="index.php?page=reports&amp;report=<?= urlencode($report_key); ?>">Reset</a></div>
 </div></form>
 <div class="row g-3 mb-4"><div class="col-md-4"><div class="glass-card p-4 h-100"><small class="text-secondary">CURRENT REPORT</small><h5 class="mt-2 mb-0"><?= htmlspecialchars($report[0]); ?></h5></div></div><div class="col-md-4"><div class="glass-card p-4 h-100"><small class="text-secondary">MATCHING RECORDS</small><h3 class="mt-2 mb-0"><?= number_format($result['total']); ?></h3></div></div><div class="col-md-4"><div class="glass-card p-4 h-100"><small class="text-secondary"><?= $money?'TOTAL AMOUNT':'TOTAL VALUE'; ?></small><h3 class="mt-2 mb-0"><?= $money?'PHP ':''; ?><?= number_format($result['amount'],2); ?><?= $report_key==='training_attendance'?' combined %':''; ?></h3></div></div></div>
 <div class="glass-card p-3 mb-4"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Date</th><th>Employee</th><th>Department</th><th>Status</th><th>Type</th><th>Amount / Value</th><th>Details</th></tr></thead><tbody>
 <?php if(!$result['rows']):?><tr><td colspan="7"><div class="text-center text-secondary py-5"><i class="fa-solid fa-chart-column fa-2x d-block mb-3"></i>No real database records match this report and filter.</div></td></tr><?php endif;?>
 <?php foreach($result['rows'] as $row):?><tr><td><?= htmlspecialchars($row['event_date']??'N/A'); ?></td><td><strong><?= htmlspecialchars($row['employee']); ?></strong><small class="d-block text-secondary"><?= htmlspecialchars($row['employee_code']); ?></small></td><td><?= htmlspecialchars($row['department']??''); ?></td><td><span class="badge badge-soft-info"><?= htmlspecialchars($row['status']??''); ?></span></td><td><?= htmlspecialchars($row['type']??''); ?></td><td><?= $row['amount']!==null?($money?'PHP ':'').number_format((float)$row['amount'],2):''; ?></td><td class="small"><?= htmlspecialchars($row['detail']??''); ?></td></tr><?php endforeach;?>
 </tbody></table></div></div>
 <?php if($result['pages']>1):?><nav><ul class="pagination justify-content-center"><?php for($p=1;$p<=$result['pages'];$p++):$pageQuery=$query;$pageQuery['page']='reports';$pageQuery['report']=$report_key;$pageQuery['p']=$p;?><li class="page-item <?= $p===$result['page']?'active':''; ?>"><a class="page-link" href="?<?= htmlspecialchars(http_build_query($pageQuery)); ?>"><?= $p; ?></a></li><?php endfor;?></ul></nav><?php endif;?>
</div><?php require APP_PATH.'Views/layouts/footer.php'; ?>
